# Generated by Django 3.0.8 on 2020-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
